# Generated by Django 5.2.7 on 2025-10-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_book_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sách', 'verbose_name_plural': 'Quản lý sách'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='available',
        ),
        migrations.RemoveField(
            model_name='book',
            name='copies',
        ),
        migrations.AddField(
            model_name='book',
            name='available_copies',
            field=models.PositiveIntegerField(default=1, verbose_name='Số bản còn lại'),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Thể loại'),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AddField(
            model_name='book',
            name='total_copies',
            field=models.PositiveIntegerField(default=1, verbose_name='Tổng số bản'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Tác giả'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tên sách'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Năm xuất bản'),
        ),
    ]
