# Generated by Django 5.0.6 on 2025-10-27 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0004_penaltyhistory'),
        ('manager', '0006_alter_book_options_remove_book_available_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sách', 'verbose_name_plural': '📚 Quản lý sách'},
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/', verbose_name='Ảnh bìa'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày thêm'),
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Lý do phạt')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Số tiền phạt (VNĐ)')),
                ('cleared', models.BooleanField(default=False, verbose_name='Đã thanh toán')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày lập')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_penalties', to='borrower.loan', verbose_name='Phiếu mượn liên quan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người bị phạt')),
            ],
            options={
                'verbose_name': 'Phiếu phạt',
                'verbose_name_plural': '⚠️ Quản lý phiếu phạt',
                'ordering': ['-created_at'],
            },
        ),
    ]
