# Generated by Django 5.0.6 on 2025-10-28 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0005_remove_penaltyhistory_penalty_and_more'),
        ('manager', '0008_alter_book_options_alter_penalty_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalty',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_penalties', to='borrower.loan', verbose_name='Phiếu mượn liên quan'),
        ),
    ]
