# Generated by Django 5.0.6 on 2025-10-30 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_alter_penalty_loan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_code', models.CharField(max_length=20, unique=True, verbose_name='Mã quản lý')),
                ('email', models.EmailField(max_length=254, verbose_name='Email liên hệ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hồ sơ quản lý',
                'verbose_name_plural': 'Hồ sơ quản lý',
            },
        ),
    ]
