# Generated by Django 5.2.7 on 2025-10-09 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_book_quantity_remove_borrow_due_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='return',
            old_name='returned_at',
            new_name='return_date',
        ),
        migrations.AlterField(
            model_name='return',
            name='borrow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.borrow'),
        ),
    ]
