# Generated by Django 5.2.7 on 2025-10-18 06:47

import borrower.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='due_date',
        ),
        migrations.AddField(
            model_name='loan',
            name='due_date',
            field=models.DateTimeField(default=borrower.models.default_due_date),
        ),
    ]
