# Generated by Django 5.0.6 on 2025-10-28 06:53

import borrower.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0004_penaltyhistory'),
        ('manager', '0007_alter_book_options_alter_book_cover_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penaltyhistory',
            name='penalty',
        ),
        migrations.RemoveField(
            model_name='penaltyhistory',
            name='action_by',
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-borrowed_at'], 'verbose_name': 'Phiếu mượn', 'verbose_name_plural': '📘 Danh sách phiếu mượn'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Hồ sơ người mượn', 'verbose_name_plural': '👤 Hồ sơ người mượn'},
        ),
        migrations.AlterField(
            model_name='loan',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.book', verbose_name='Sách mượn'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='borrowed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày mượn'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateTimeField(default=borrower.models.default_due_date, verbose_name='Hạn trả'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='returned',
            field=models.BooleanField(default=False, verbose_name='Đã trả'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày trả'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người mượn'),
        ),
        migrations.DeleteModel(
            name='Penalty',
        ),
        migrations.DeleteModel(
            name='PenaltyHistory',
        ),
    ]
